title: 'For sale'
fields:
      -
        handle: price
        field:
          type: money
          display: Price
          required: true
          listable: true
          validate:
            - min:0
          width: '25'
      -
        handle: tax_id
        field:
          display: Tax
          type: tax
          required: true
          listable: false
          width: '25'
      -
        handle: shipping_profile_slug
        field:
          display: Shipping
          type: shipping
          required: true
          listable: false
          width: '25'
      -
        handle: images
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          type: assets
          listable: true
          display: Images
          validate:
            - nullable
      -
        handle: variants
        field:
          type: variants
          listable: hidden
          display: Variants
      -
        handle: categories
        field:
          type: categories
          listable: hidden
          display: Categories
      -
        handle: stock
        field:
          type: integer
          width: 50
          default: 0
          listable: true
          display: Stock
          validate:
            - required
            - integer
          unless:
            stock_unlimited: 'equals true'
      -
        handle: stock_unlimited
        field:
          type: toggle
          width: 50
          listable: true
          display: 'Stock Unlimited'
          validate:
            - required
            - boolean

