title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
            - string
          listable: true
          input_type: text
          width: 50
      -
        handle: type
        field:
          input_type: text
          antlers: false
          display: Type
          type: text
          icon: text
          width: 50
          listable: hidden
      -
        handle: price
        field:
          type: money
          display: Price
          listable: true
          validate:
            - required
            - 'min:0'
          width: '25'
      -
        handle: description
        field:
          antlers: true
          display: Description
          type: textarea
          icon: textarea
          listable: hidden
      -
        handle: tax_id
        field:
          display: Tax
          type: tax
          listable: false
          width: '25'
          validate:
            - required
      -
        handle: shipping_profile_slug
        field:
          display: Shipping
          type: shipping
          listable: false
          width: '25'
          validate:
            - required
      -
        handle: images
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          type: assets
          listable: true
          display: Images
          validate:
            - nullable
      -
        handle: variants
        field:
          type: variants
          listable: hidden
          display: Variants
      -
        handle: categories
        field:
          type: categories
          listable: hidden
          display: Categories
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: stock
        field:
          type: integer
          width: 50
          default: 0
          listable: true
          display: Stock
          validate:
            - required
            - integer
          unless:
            stock_unlimited: 'equals true'
      -
        handle: stock_unlimited
        field:
          type: toggle
          width: 50
          listable: true
          display: 'Stock Unlimited'
          validate:
            - required
            - boolean
      -
        handle: parent
        field:
          type: entries
          collections:
            - products
          max_items: 1
          listable: false
          localizable: true
  programs:
    display: Programs
    fields:
      -
        handle: which_class
        field:
          inline: true
          options:
            '4.7': 'Laser 4.7'
            Radial: 'Laser Radial'
            'Full Rig': 'Laser Full Rig'
            Kite: Kite
            Foil: Foil
          display: 'Which class'
          type: checkboxes
          icon: checkboxes
          listable: hidden
      -
        handle: coach
        field:
          mode: select
          display: Coach
          type: users
          icon: users
          listable: hidden
  process:
    display: Process
    fields:
      -
        handle: process_description
        field:
          always_show_set_button: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: true
          fullscreen: true
          allow_source: true
          display: 'Process description'
          type: bard
          icon: bard
          listable: hidden
      -
        handle: quote
        field:
          antlers: false
          display: Quote
          type: textarea
          icon: textarea
          listable: hidden
      -
        handle: quote_description
        field:
          antlers: false
          display: 'Quote description'
          type: textarea
          icon: textarea
          listable: hidden
      -
        handle: quote_logo
        field:
          mode: grid
          container: assets
          folder: img/logo
          restrict: true
          allow_uploads: true
          max_files: 1
          display: 'Quote logo'
          type: assets
          icon: assets
          listable: hidden
